### ISSUE TITLE
Update dependencies for 8.8.1

### ISSUE THREAD

**Issue by mgajda** [migamake/json-autotype#32]
CI seems to complain:
https://travis-ci.org/mgajda/json-autotype/jobs/579141334

https://gitlab.com/migamake/json-autotype/commits/master

**Comment by mgajda** [comment]
Updated dependencies for `lens<4.19` and `hashable<1.4.0` just now.
We can release `json-autotype` version `3.0.1` as soon as it passes CI with GHC 8.8.1

**Comment by sigrlami** [comment]
Due to https://github.com/migamake/json-autotype/pull/39#issuecomment-607900337 this should be closed
